version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: musicshop_db
    restart: always
    environment:
      POSTGRES_DB: musicshop_db
      POSTGRES_USER: musicshop
      POSTGRES_PASSWORD: S3cret
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local